version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ../my-cloud:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ../my-cloud:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: mycloud
      POSTGRES_USER: mycloud
      POSTGRES_PASSWORD: mycloud123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:

